version: '3'
services:


  mysql:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_ROOT_USER: 'root'
        MYSQL_PASSWORD: 'root'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  php:
    build:
      context: ./php
      args:
        USER: '${USER_NAME}'
        USER_ID: ${USER_ID} 
        USER_GID: ${GROUP_ID}
    depends_on:
      - mysql
    volumes:
      - ${WORK_PATH}:/var/www

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "3030:3030"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.index.html:/var/www/html/index.html
      - ${WORK_PATH}:/var/www
    depends_on:
      - php
volumes:
  mysqldata: {}    

networks:
  default:
    driver: bridge
